
[Vanilla]
	#Display stat bar for armor
	armorStat = true
	#Display stat bar for tools
	toolStat = true
	#Display tooltip for crafting-only items
	vanillaMaterials = true
	#Display stat bar for swords
	swordStat = true

#The following settings only affect Obscuria Collection Mods and do not conflict or overlap with other Tooltip Mods
[Collection]

	[Collection.General]
		#Display tooltip for crafting-only items
		collectionMaterials = true
		#Display souls for special items (forge:tooltips/souls)
		soulsBar = true
		#Display durability for special items (forge:tooltips/durability)
		durabilityBar = true
		#Display charge for special items (forge:tooltips/charge)
		chargeBar = true

	[Collection.Essentials]
		#Display common item descriptions
		essentialsTooltips = true
		#Display usage tips for some items
		essentialsTips = true

	[Collection.Aquamirae]
		#Display common item descriptions
		aquamiraeTooltips = true
		#Display usage tips for some items
		aquamiraeTips = true

